### ISSUE TITLE
ive done the rating thing and the uh secret obby thingy and it just kills you and ends it

### ISSUE THREAD

**Issue by elelelelels** [Encythe/bg-issuetracker#2]
### Checklist

- [X] I have **checked both [open and closed issues](https://github.com/Bauspicious-Games/bg-issuetracker/issues?q=is%3Aissue+label%3Abug)** to ensure this bug hasn't already been reported.
- [X] My server is on the **latest version**.
- [X] I am certain this is a **bug report**, not a suggestion.

### Severity

Minor

### Game

Not JJT Upgrade Tree

### Reproduction Steps

just activate the rating thing, and whn the dellusion challenge begins it just doesnt work and kills you after a while

### Current vs Expected behavior

just make it so it wont kill you if youre in the delusion thingy, ive waited  so long for it just to combust because of this

**Comment by Encythe** [comment]
This is expected behavior. "Ratings" kills you after it reaches 0, so if you started Delusion, your loss lol
